In [1]:
import pandas as pd
import numpy as np
import json 
from io import StringIO

In [2]:
# Create sample transaction data (realistic retail format)
transactions_csv = """transaction_id,store_id,date,product_id,product_name,quantity,amount,payment_method
T001,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,2,4.98,CARD
T002,ST_NYC,2024-06-14,SKU_002,Pepsi 1.5L,1,2.49,CASH
T003,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,1,2.49,CARD
T004,ST_LA,2024-06-14,SKU_001,Coca-Cola 2L,5,12.45,CARD
T005,ST_LA,2024-06-14,SKU_003,Sprite 1L,3,8.97,CASH
T006,ST_NYC,2024-06-15,SKU_001,Coca-Cola 2L,,6.97,CARD
T007,ST_NYC,2024-06-15,SKU_004,Fanta Orange,2,3.98,DEBIT
T008,ST_LA,2024-06-15,SKU_001,Coca-Cola 2L,1,2.49,CARD
T009,ST_CHI,2024-06-15,SKU_002,Pepsi 1.5L,4,9.96,CASH
T010,ST_CHI,2024-06-15,SKU_001,Coca-Cola 2L,6,14.94,CARD
T001,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,2,4.98,CARD"""  # DUPLICATE (T001 appears twice)

In [43]:
df = pd.read_csv(StringIO(transactions_csv))
df

,transaction_id,store_id,date,product_id,product_name,quantity,amount,payment_method
0,T001,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,2.0,4.98,CARD
1,T002,ST_NYC,2024-06-14,SKU_002,Pepsi 1.5L,1.0,2.49,CASH
2,T003,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,1.0,2.49,CARD
3,T004,ST_LA,2024-06-14,SKU_001,Coca-Cola 2L,5.0,12.45,CARD
4,T005,ST_LA,2024-06-14,SKU_003,Sprite 1L,3.0,8.97,CASH
5,T006,ST_NYC,2024-06-15,SKU_001,Coca-Cola 2L,NaN,6.97,CARD
6,T007,ST_NYC,2024-06-15,SKU_004,Fanta Orange,2.0,3.98,DEBIT
7,T008,ST_LA,2024-06-15,SKU_001,Coca-Cola 2L,1.0,2.49,CARD
8,T009,ST_CHI,2024-06-15,SKU_002,Pepsi 1.5L,4.0,9.96,CASH
9,T010,ST_CHI,2024-06-15,SKU_001,Coca-Cola 2L,6.0,14.94,CARD
10,T001,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,2.0,4.98,CARD

In [44]:
print("="*80)
print("SAMPLE DATA LOADED")
print("="*80)
print(df.head())
print(f"\nData frame shape: {df.shape}")
print(f"\nNumber of nulls: {df.isnull().sum()}")

================================================================================
SAMPLE DATA LOADED
================================================================================
  transaction_id store_id        date product_id  product_name  quantity  \
0           T001   ST_NYC  2024-06-14    SKU_001  Coca-Cola 2L       2.0
1           T002   ST_NYC  2024-06-14    SKU_002    Pepsi 1.5L       1.0
2           T003   ST_NYC  2024-06-14    SKU_001  Coca-Cola 2L       1.0
3           T004    ST_LA  2024-06-14    SKU_001  Coca-Cola 2L       5.0
4           T005    ST_LA  2024-06-14    SKU_003     Sprite 1L       3.0

   amount payment_method
0    4.98           CARD
1    2.49           CASH
2    2.49           CARD
3   12.45           CARD
4    8.97           CASH

Data frame shape: (11, 8)

Number of nulls: transaction_id    0
store_id          0
date              0
product_id        0
product_name      0
quantity          1
amount            0
payment_method    0
dtype: int64

In [15]:
print("\n" + "=" * 80)
print("EXERCISE 1: Data Exploration & Cleaning")
print("=" * 80)
print("""TASK:
1. Check data types
2. Identify missing values
3. Find and remove duplicates
4. Calculate basic statistics""")

================================================================================
EXERCISE 1: Data Exploration & Cleaning
================================================================================
TASK:
1. Check data types
2. Identify missing values
3. Find and remove duplicates
4. Calculate basic statistics

In [57]:
print(f"Data Types:\n{df.info()}")
print(f"\nMissing values:\n{df.isnull().sum()}")
print(f"\nStatistics summary:\n{df.describe()}")

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  10 non-null     str
 1   store_id        10 non-null     str
 2   date            10 non-null     str
 3   product_id      10 non-null     str
 4   product_name    10 non-null     str
 5   quantity        9 non-null      float64
 6   amount          10 non-null     float64
 7   payment_method  10 non-null     str
dtypes: float64(2), str(6)
memory usage: 772.0 bytes
Data Types:
None

Missing values:
transaction_id    0
store_id          0
date              0
product_id        0
product_name      0
quantity          1
amount            0
payment_method    0
dtype: int64

Statistics summary:
       quantity     amount
count  9.000000  10.000000
mean   2.777778   6.972000
std    1.855921   4.467198
min    1.000000   2.490000
25%    1.000000   2.862500
50%    2.000000   5.975000
75%    4.000000   9.712500
max    6.000000  14.940000

In [50]:
df=df.drop_duplicates()

In [61]:
missing=df.isnull().sum()
print(missing[missing>0])

quantity    1
dtype: int64

In [66]:
print("\n" + "=" * 80)
print("EXERCISE 2: Filtering & Aggregation")
print("=" * 80)
print("""
TASK:
1. Filter transactions from store ST_NYC
2. Calculate total sales by store
3. Calculate total sales by product
4. Find the top 3 products by revenue""")

================================================================================
EXERCISE 2: Filtering & Aggregation
================================================================================

TASK:
1. Filter transactions from store ST_NYC
2. Calculate total sales by store
3. Calculate total sales by product
4. Find the top 3 products by revenue

In [70]:
df.head()
df[df["store_id"]=="ST_NYC"]
df.groupby('store_id')['amount'].sum().sort_values(ascending=False)

store_id
ST_CHI    24.90
ST_LA     23.91
ST_NYC    20.91
Name: amount, dtype: float64

In [74]:
print(df.head())
by_productby=df.groupby('product_id')['amount'].sum().sort_values(ascending=False)
print(by_productby)

  transaction_id store_id        date product_id  product_name  quantity  \
0           T001   ST_NYC  2024-06-14    SKU_001  Coca-Cola 2L       2.0
1           T002   ST_NYC  2024-06-14    SKU_002    Pepsi 1.5L       1.0
2           T003   ST_NYC  2024-06-14    SKU_001  Coca-Cola 2L       1.0
3           T004    ST_LA  2024-06-14    SKU_001  Coca-Cola 2L       5.0
4           T005    ST_LA  2024-06-14    SKU_003     Sprite 1L       3.0

   amount payment_method
0    4.98           CARD
1    2.49           CASH
2    2.49           CARD
3   12.45           CARD
4    8.97           CASH
product_id
SKU_001    44.32
SKU_002    12.45
SKU_003     8.97
SKU_004     3.98
Name: amount, dtype: float64

In [ ]:
top3=df.groupby('product_id').agg({
    'product_name': 'first',
    'amount': 'sum',
    'quantity':'sum',
    'transaction_id': 'count'
}).sort_values('amount',ascending=False).head(3)
top3.columns=['product_name','total_revenue','total_quantity','no_of_orders']
print(top3)

            product_name  total_revenue  total_quantity  no_of_orders
product_id
SKU_001     Coca-Cola 2L          44.32            15.0             6
SKU_002       Pepsi 1.5L          12.45             5.0             2
SKU_003        Sprite 1L           8.97             3.0             1

In [78]:
top3=df.groupby('product_id')['amount'].sum().sort_values(ascending=False).head(3)
print(top3)

product_id
SKU_001    44.32
SKU_002    12.45
SKU_003     8.97
Name: amount, dtype: float64

In [79]:
# ============================================================================
# EXERCISE 3: DATA TYPE CONVERSION & TIME SERIES
# ============================================================================

print("\n" + "=" * 80)
print("EXERCISE 3: DateTime & Time-Based Analysis")
print("=" * 80)
print("""
TASK:
1. Convert 'date' column to datetime
2. Extract day of week
3. Calculate daily sales by store
4. Find which day had highest sales

HINTS:
- Use pd.to_datetime() for conversion
- Use .dt.day_name() for day of week
- Use groupby(['date', 'store_id']).agg() for daily sales
""")

================================================================================
EXERCISE 3: DateTime & Time-Based Analysis
================================================================================

TASK:
1. Convert 'date' column to datetime
2. Extract day of week
3. Calculate daily sales by store
4. Find which day had highest sales

HINTS:
- Use pd.to_datetime() for conversion
- Use .dt.day_name() for day of week
- Use groupby(['date', 'store_id']).agg() for daily sales

In [94]:
df['date']=pd.to_datetime(df['date'])
df['week']=df['date'].dt.day_of_week
df

,transaction_id,store_id,date,product_id,product_name,quantity,amount,payment_method,week
0,T001,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,2.0,4.98,CARD,4
1,T002,ST_NYC,2024-06-14,SKU_002,Pepsi 1.5L,1.0,2.49,CASH,4
2,T003,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,1.0,2.49,CARD,4
3,T004,ST_LA,2024-06-14,SKU_001,Coca-Cola 2L,5.0,12.45,CARD,4
4,T005,ST_LA,2024-06-14,SKU_003,Sprite 1L,3.0,8.97,CASH,4
5,T006,ST_NYC,2024-06-15,SKU_001,Coca-Cola 2L,NaN,6.97,CARD,5
6,T007,ST_NYC,2024-06-15,SKU_004,Fanta Orange,2.0,3.98,DEBIT,5
7,T008,ST_LA,2024-06-15,SKU_001,Coca-Cola 2L,1.0,2.49,CARD,5
8,T009,ST_CHI,2024-06-15,SKU_002,Pepsi 1.5L,4.0,9.96,CASH,5
9,T010,ST_CHI,2024-06-15,SKU_001,Coca-Cola 2L,6.0,14.94,CARD,5

In [114]:
df_store=df.groupby(['date','store_id']).agg({
    'amount':'sum',
    'quantity':'sum',
    'transaction_id':'count'
}).reset_index()
df_store.columns = ['Date', 'Store', 'Total_Sales', 'Total_Qty', 'Num_Transactions']
print(df_store)

        Date   Store  Total_Sales  Total_Qty  Num_Transactions
0 2024-06-14   ST_LA        21.42        8.0                 2
1 2024-06-14  ST_NYC         9.96        4.0                 3
2 2024-06-15  ST_CHI        24.90       10.0                 2
3 2024-06-15   ST_LA         2.49        1.0                 1
4 2024-06-15  ST_NYC        10.95        2.0                 2

In [118]:
df.head()
df_highest=df.groupby('date')['amount'].sum().sort_values(ascending=False).head(1)
print(df_highest)

date
2024-06-15    38.34
Name: amount, dtype: float64

In [119]:
print("\n" + "=" * 80)
print("EXERCISE 5: Missing Data Handling")
print("=" * 80)
print("""
TASK:
The original data had missing values (quantity = NaN in row T006).

STRATEGY:
1. Count missing values
2. Decide: fill or drop?
3. For quantity: fill with average (assumption: 1 unit if missing)
4. For amounts: drop (can't calculate without knowing quantity)
5. Validate cleaned data

HINTS:
- Use df.isnull().sum() to count
- Use df.fillna() to fill with value/method
- Use df.dropna() to remove rows with NaN
""")

================================================================================
EXERCISE 5: Missing Data Handling
================================================================================

TASK:
The original data had missing values (quantity = NaN in row T006).

STRATEGY:
1. Count missing values
2. Decide: fill or drop?
3. For quantity: fill with average (assumption: 1 unit if missing)
4. For amounts: drop (can't calculate without knowing quantity)
5. Validate cleaned data

HINTS:
- Use df.isnull().sum() to count
- Use df.fillna() to fill with value/method
- Use df.dropna() to remove rows with NaN

In [124]:
df.isnull().sum()
df=df.fillna(df['quantity'].mean())

In [126]:
df.dropna(subset='amount',inplace=True)

In [127]:
df

,transaction_id,store_id,date,product_id,product_name,quantity,amount,payment_method,week
0,T001,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,2.0,4.98,CARD,4
1,T002,ST_NYC,2024-06-14,SKU_002,Pepsi 1.5L,1.0,2.49,CASH,4
2,T003,ST_NYC,2024-06-14,SKU_001,Coca-Cola 2L,1.0,2.49,CARD,4
3,T004,ST_LA,2024-06-14,SKU_001,Coca-Cola 2L,5.0,12.45,CARD,4
4,T005,ST_LA,2024-06-14,SKU_003,Sprite 1L,3.0,8.97,CASH,4
5,T006,ST_NYC,2024-06-15,SKU_001,Coca-Cola 2L,2.0,6.97,CARD,5
6,T007,ST_NYC,2024-06-15,SKU_004,Fanta Orange,2.0,3.98,DEBIT,5
7,T008,ST_LA,2024-06-15,SKU_001,Coca-Cola 2L,1.0,2.49,CARD,5
8,T009,ST_CHI,2024-06-15,SKU_002,Pepsi 1.5L,4.0,9.96,CASH,5
9,T010,ST_CHI,2024-06-15,SKU_001,Coca-Cola 2L,6.0,14.94,CARD,5